### ISSUE TITLE
大佬 脚本粘进去 打开boss直聘没啥反应呢

### ISSUE THREAD

**Issue by WangZhiChao66** [yangfeng20/boss_batch_push#1]

**Comment by yangfeng20** [comment]
你保存没哟，新建一个脚本，然后按ctrl+s保存。
你看看脚本管理页面有没有。

**Comment by WangZhiChao66** [comment]
保存了 但是点批量投递没啥反应

**Comment by yangfeng20** [comment]
哦哦，页面已经有变化了是吧。你可以把f12打开，看看控制台。

**Comment by WangZhiChao66** [comment]
<img width="499" alt="image" src="https://github.com/yangfeng20/boss_batch_push/assets/69849636/a2cf045a-59a4-4c6a-acba-824c6dfe7a7c">
配置什么都没加  
<img width="868" alt="image" src="https://github.com/yangfeng20/boss_batch_push/assets/69849636/bcfefeef-1983-417a-9642-0cf43dda2e32">

**Comment by WangZhiChao66** [comment]
好的 我试下

**Comment by yangfeng20** [comment]
怎么样，可以了不

**Comment by WangZhiChao66** [comment]
不可以 直接没有那个弹窗了😂

**Comment by yangfeng20** [comment]
新版本已经更新

**Comment by yangfeng20** [comment]
新版本修复了
