### ISSUE TITLE
投递时自动发送打招呼语句, 而不是使用默认语句

### ISSUE THREAD

**Issue by AndACat** [yangfeng20/boss_batch_push#12]
亲爱的开发者您好, 能否支持一下投递时自动发送打招呼语句, 而不是默认语句
默认语句: 您好，可以聊聊吗？您这个职位我很有兴趣，希望进一步了解
能追加发送语句为常用语 第一条吗 这样就不用再每个发送语句了: 
![image](https://github.com/yangfeng20/boss_batch_push/assets/44843774/7d720300-33ad-44b1-ab43-3dd173f1e805)

谢谢!

**Comment by yangfeng20** [comment]
这个发送的语句，应该是您设置的打招呼语句呢，您可以尝试在手机端修改常用语句，然后再尝试投递。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 上午9:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [yangfeng20/boss_batch_push] 投递时自动发送打招呼语句, 而不是使用默认语句 (Issue #12)





 
亲爱的开发者您好, 能否支持一下投递时自动发送打招呼语句, 而不是默认语句
 默认语句: 您好，可以聊聊吗？您这个职位我很有兴趣，希望进一步了解
 能追加发送语句:
 
 
谢谢!

**Comment by AndACat** [comment]
您好, 在boss直聘上使用打招呼语句只能选择固定的, 我想能够支持自定义打招呼语句, 但其不支持, 希望作者能够加入此功能~
![52cf5b395db7a7c23b1e80f1259a939](https://github.com/yangfeng20/boss_batch_push/assets/44843774/f8484f08-bd38-463f-b77a-2024e0111bb9)

**Comment by yangfeng20** [comment]
我可以这样理解吗，就是您在手机是可以选择boss支持的几种打招呼方式，并且可以同步到web端；但是你想使用的是自定义的打招呼语句，boss不支持将你的自定义打招呼语句设置为默认的。
&nbsp;


maple
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 下午3:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangfeng20/boss_batch_push] 投递时自动发送打招呼语句, 而不是使用默认语句 (Issue #12)





 
您好, 在boss直聘上使用打招呼语句只能选择固定的, 我想能够支持自定义打招呼语句, 但其不支持, 希望作者能够加入此功能~

**Comment by AndACat** [comment]
是的, 您理解的非常正确, 我希望该油猴插件能够支持自动投递简历的时候, 发送boss自带的无法自定义的打招呼语, **同时!** 也能携带发送常用语的第一条语句给对方的HR, 如下图:
![image](https://github.com/yangfeng20/boss_batch_push/assets/44843774/0c99ee6a-3594-43d3-a133-885279bc1f91)

**Comment by yangfeng20** [comment]
好的，我已经明白了您的需求，最近我会看看的。能够实现的话，会通知您的。
&nbsp;


maple
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月18日(星期一) 下午3:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangfeng20/boss_batch_push] 投递时自动发送打招呼语句, 而不是使用默认语句 (Issue #12)





 
是的, 您理解的非常正确, 我希望该油猴插件能够支持自动投递简历的时候, 发送boss自带的无法自定义的打招呼语, 同时! 也能携带发送常用语的第一条语句给对方的HR, 如下图:

**Comment by AndACat** [comment]
谢谢您Thanks♪(･ω･)ﾉ

**Comment by yangfeng20** [comment]
您好，这个功能已经实现了，您可以直接升级版本为1.1.9即可。
https://greasyfork.org/zh-CN/scripts/468125-boss-batch-push-boss%E7%9B%B4%E8%81%98%E6%89%B9%E9%87%8F%E6%8A%95%E7%AE%80%E5%8E%86
开发这个功能还真是用了不少精力，你可以看看这期的更新日志。

**Comment by AndACat** [comment]
我试了一下， 感觉非常棒！
以前的时候，在使用完您的插件后还需要再手动给对方发自定义的自我介绍，非常麻烦，现在完全不在需要了，真是太好了！
1.1.9在我认为是一个里程碑式版本！

**Comment by yangfeng20** [comment]
可以的，感谢您的认可
