### ISSUE TITLE
为什么一直显示不满足条件

### ISSUE THREAD

**Issue by Louis24** [yangfeng20/boss_batch_push#14]

**Comment by yangfeng20** [comment]
方便截个图吗，你这也我也我不知道什么情况

**Comment by Louis24** [comment]
![image](https://github.com/yangfeng20/boss_batch_push/assets/18719360/cb344d38-5e54-4986-95a7-2f8bdb03b07d)
我以为是代码里写的提示

**Comment by yangfeng20** [comment]
这个是boss的限制；个人的简介和岗位介绍差别太多，boss就会直接限制投递。

**Comment by Louis24** [comment]
那为什么手机端可以
________________________________
发件人: 杨锋 ***@***.***>
发送时间: 2023年10月9日 0:42
收件人: yangfeng20/boss_batch_push ***@***.***>
抄送: Louis Li ***@***.***>; Author ***@***.***>
主题: Re: [yangfeng20/boss_batch_push] 为什么一直显示不满足条件 (Issue #14)


这个是boss的限制；个人的简介和岗位介绍差别太多，boss就会直接限制投递。

―

**Comment by yangfeng20** [comment]
你可以在web端手动投递一下试试，他会有一个弹框拦截的

**Comment by Louis24** [comment]
哦哦好吧谢啦
