### ISSUE TITLE
批量投递，同一个企业会打招呼多次

### ISSUE THREAD

**Issue by QQQ300kuai** [yangfeng20/boss_batch_push#15]
前后两天投递，同一个企业会打招呼多次

**Comment by yangfeng20** [comment]
可以的，最近有时间我看看，不过最好能够提供是在什么场景下复现的，我之前试了下，并不能复现这个bug

**Comment by QQQ300kuai** [comment]
> 可以的，最近有时间我看看，不过最好能够提供是在什么场景下复现的，我之前试了下，并不能复现这个bug

两种情况下出现
第一种情况:当天批量投递，就重复发送了。可能是同一个企业，发了多个应聘信息？
第二种情况:前后两天投递，昨天已经投过的企业，今天批量投递的时候没有被过滤掉，重复投了，再次打招呼

**Comment by yangfeng20** [comment]
请查看这个issues：https://github.com/yangfeng20/boss_batch_push/issues/16
