### ISSUE TITLE
现在是23年11月末，好像又用不了了

### ISSUE THREAD

**Issue by NicoPasta** [yangfeng20/boss_batch_push#19]
能说说这东西大概原理是啥吗，自己改了半天没啥用。。。脚本执行后log一个“未读取到本地配置”，然后页面也没有变化

**Comment by yangfeng20** [comment]
如果是第一次使用就是没有配置的，你可以现在页面配置你的筛选项然后保存就有了。
你说的用不了，是什么效果呢。页面有批量投递的按钮吗

**Comment by NicoPasta** [comment]
> 如果是第一次使用就是没有配置的，你可以现在页面配置你的筛选项然后保存就有了。 你说的用不了，是什么效果呢。页面有批量投递的按钮吗

DOM没append上去，但我看了下operatePanel的init是执行了的，还在看为什么

**Comment by NicoPasta** [comment]
> 如果是第一次使用就是没有配置的，你可以现在页面配置你的筛选项然后保存就有了。 你说的用不了，是什么效果呢。页面有批量投递的按钮吗

代码执行了，但是页面没有变化

**Comment by yangfeng20** [comment]
控制台有报错吗，你访问的url是那个。

**Comment by NicoPasta** [comment]
> 控制台有报错吗，你访问的url是那个。

没报错

**Comment by NicoPasta** [comment]
> 控制台有报错吗，你访问的url是那个。

没报错，web/geek/job-recommend, 不过我看你用的includes(web/geek/job)，应该没影响，能匹配到

**Comment by yangfeng20** [comment]
我这边访问没问题，你刷新下试试
![image](https://github.com/yangfeng20/boss_batch_push/assets/83114564/66fd6ff1-2257-4e5b-a339-6af245d4ee13)

**Comment by yangfeng20** [comment]
这个页面是不支持的
![image](https://github.com/yangfeng20/boss_batch_push/assets/83114564/434d70f2-d4d6-4d25-9762-321feb8d8fad)

**Comment by NicoPasta** [comment]
> 这个页面是不支持的 ![image](https://private-user-images.githubusercontent.com/83114564/286161198-434d70f2-d4d6-4d25-9762-321feb8d8fad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTUyNTgsIm5iZiI6MTcwMTE1NDk1OCwicGF0aCI6Ii84MzExNDU2NC8yODYxNjExOTgtNDM0ZDcwZjItZDRkNi00ZDI1LTk3NjItMzIxZmViOGQ4ZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYzk1ZmMyNTE1Zjk1Zjc3ZDQyY2Q0YTllOGQ1ODYwMGIzNTgzNmFhZGJmNTMyZmY2MDRjMThjZmExZTc2ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rQX1roUGFtrT-hEqmBNRQ-YUxZhK3t1ItCU5pb72Ut0)

怪不得，我就是用的这个页面

**Comment by iconFehu** [comment]
> > 这个页面是不支持的 ![image](https://private-user-images.githubusercontent.com/83114564/286161198-434d70f2-d4d6-4d25-9762-321feb8d8fad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTUyNTgsIm5iZiI6MTcwMTE1NDk1OCwicGF0aCI6Ii84MzExNDU2NC8yODYxNjExOTgtNDM0ZDcwZjItZDRkNi00ZDI1LTk3NjItMzIxZmViOGQ4ZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYzk1ZmMyNTE1Zjk1Zjc3ZDQyY2Q0YTllOGQ1ODYwMGIzNTgzNmFhZGJmNTMyZmY2MDRjMThjZmExZTc2ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rQX1roUGFtrT-hEqmBNRQ-YUxZhK3t1ItCU5pb72Ut0)
> 
> 怪不得，我就是用的这个页面

那么需要在哪个页面才可以使用呢

**Comment by iconFehu** [comment]
@yangfeng20 那个自定义招呼语可以改成多行输出框吗

**Comment by yangfeng20** [comment]
https://www.zhipin.com/web/geek/job
这可以

**Comment by yangfeng20** [comment]
@iconFehu 
https://www.zhipin.com/web/geek/job

**Comment by iconFehu** [comment]
@yangfeng20 好的，我刚刚自己乱点了下，点首页后搜索岗位就出来了。感谢。刚开始不知道怎么使用🤣
