### ISSUE TITLE
还是很感谢大佬的脚本的

### ISSUE THREAD

**Issue by Ocyss** [yangfeng20/boss_batch_push#2]
有些地方我自己改了下，算了丢后台无感投递了，不然老是前台弹出来很难受。
gf那也留言了，刚看到还有GitHub，如果可以，不妨加个好友互相交流交流，不过像作者这么厉害的人，应该已经找到满意的工作了~~
![image](https://github.com/yangfeng20/boss_batch_push/assets/68412205/c3c72e89-f5ad-434b-9a7c-2f6b4d981626)

**Comment by yangfeng20** [comment]
厉害的。欢迎来提pr

**Comment by yangfeng20** [comment]
wx:y_distance_poem

**Comment by yangfeng20** [comment]
关闭咯
