### ISSUE TITLE
发现个小bug，最后一条打招呼的招呼语可能连续发送多次

### ISSUE THREAD

**Issue by Kiraaaaaaa** [yangfeng20/boss_batch_push#29]
最后一个打招呼的招呼语发送了22次，最后面几个打招呼没有发送招呼语

**Comment by yangfeng20** [comment]
https://github.com/yangfeng20/boss_batch_push/issues/16
参考一下这个哟

**Comment by Kiraaaaaaa** [comment]
好吧，我知道了。那现在有没有技术手段可以解决这个问题呢，想了解一下

**Comment by yangfeng20** [comment]
有的啊，就是自己发送websocket，这样就不需要依赖点击页面的js了，就没问题。
