### ISSUE TITLE
感谢作者，后续可否考虑发送简历图片功能

### ISSUE THREAD

**Issue by luojiaju** [yangfeng20/boss_batch_push#31]
这个发送简历图片，这个功能非常有用
大概实现思路是：

1. 使用者提供一个简历图片链接（有效的  https://xxxx.png）
2. 通过调用booss发送图片的api发送上面的图片
3. 如果有《自定义招呼语》那么也一起发送给boss

这是我的一点意见

**Comment by yangfeng20** [comment]
我今天简单看了下，有实现的可能性。看后面的时间安排吧

**Comment by vayocc** [comment]
猎头有办法屏蔽吗？我按照公司排除某互联网,某知名,某大型 这样行吗？

**Comment by iconFehu** [comment]
@yangfeng20 那个自定义招呼语可以改成多行输出框吗

看到了已经有人修改了，https://github.com/yangfeng20/boss_batch_push/pull/18

**Comment by yangfeng20** [comment]
@iconFehu 
我看用\n和\<br>换行都是没问题的啊

![image](https://github.com/yangfeng20/boss_batch_push/assets/83114564/658ab827-6fc2-4d25-b579-67ca5cf90e32)


![image](https://github.com/yangfeng20/boss_batch_push/assets/83114564/6f7514c5-f0ca-4049-978f-37b633c197bf)

**Comment by iconFehu** [comment]
> @iconFehu 我看用\n和<br>换行都是没问题的啊
> 
> ![image](https://private-user-images.githubusercontent.com/83114564/340301087-658ab827-6fc2-4d25-b579-67ca5cf90e32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjczOTAsIm5iZiI6MTcxODYyNzA5MCwicGF0aCI6Ii84MzExNDU2NC8zNDAzMDEwODctNjU4YWI4MjctNmZjMi00ZDI1LWI1NzktNjdjYTVjZjkwZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEyMjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMjMwNzJlMjhhMzYxMzY0YWM3MmU3YmI5OWU0M2EwNDAxNjJjMjllYzczM2I1NWU4MWU5NzAyNGNkZDdhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RP4fgIAfVSaGbxUtfarPLVAITQZ78l1YdsJHZLOr_Pk)
> 
> ![image](https://private-user-images.githubusercontent.com/83114564/340300874-6f7514c5-f0ca-4049-978f-37b633c197bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjczOTAsIm5iZiI6MTcxODYyNzA5MCwicGF0aCI6Ii84MzExNDU2NC8zNDAzMDA4NzQtNmY3NTE0YzUtZjBjYS00MDQ5LTk3OGYtMzdiNjMzYzE5N2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEyMjQ1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYjYyYWEwYjIwODA1MDNiMzM4MTQ4OTU2M2ZiYTMzNWY0MmI3ZGRjY2U1ZWFkNzVmZGVhMDRmM2ZlZGJiNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1fIPEowDN-KePiiVlSiayQVVLJNM4P5eVWFv5HlsDfA)

好奇怪，我加入\n后点击保存配置然后刷新页面后点击批量投递。然后在手机上看招呼语里面确实有\n，换行失败了。

今天沟通达到上限了，怎么办，现在好想重新测试换行符能不能用

![image](https://github.com/yangfeng20/boss_batch_push/assets/46149128/d53a303f-4b73-4f76-bcca-46e78df970ab)

**Comment by yangfeng20** [comment]
web端是成功的吗，你看看

**Comment by iconFehu** [comment]
> web端是成功的吗，你看看

![CuteDragonFaintGIF](https://github.com/yangfeng20/boss_batch_push/assets/46149128/31c00855-3617-4d81-bc29-f9bcc8be15df)
我晕，发送\n的全部被我撤回了，现在WEB看不到了

**Comment by yangfeng20** [comment]
😂太惨了。没事。
明天你可以试试，如果有问题的话，你另外新提交一个issue，不然这样一直会给提出这个issue的作者发送邮件，有点打扰别人。

**Comment by yangfeng20** [comment]
这个不太好实现，需要通过websocket发送文件信息，短期应该是不会考虑了。

**Comment by yangfeng20** [comment]
图片简历的功能在新的项目中支持了。非AI功能都是免费使用的。
https://github.com/yangfeng20/ai-job
