### ISSUE TITLE
脚本很好用，有个小问题

### ISSUE THREAD

**Issue by knwceas** [yangfeng20/boss_batch_push#32]
薪资范围不起作用；
我没有开新标签招呼语还是发给了一个人好多次，下一页之后有好几个招呼语没有发出去

**Comment by yangfeng20** [comment]
薪资范围按道理不会存在问题，你是月薪还是日薪，格式是怎么样的，方便截个图吗

然后招呼语重复发送的问题。我看看最近有时间优化一版

**Comment by knwceas** [comment]
> 薪资范围按道理不会存在问题，你是月薪还是日薪，格式是怎么样的，方便截个图吗
> 
> 然后招呼语重复发送的问题。我看看最近有时间优化一版
就是筛选项的输入框，不是月薪？
![Snipaste_2024-06-07_21-15-15](https://github.com/yangfeng20/boss_batch_push/assets/48302472/f0c671e6-2d55-436b-b638-d3dea2ee05bb)

**Comment by yangfeng20** [comment]
问题已修复，更新到1.2.0版本即可使用。
对你有用的话，记得点个star
修复相关提交记录：[通过websocket发送自定义招呼语](https://github.com/yangfeng20/boss_batch_push/commit/5c7e63c95f3701aaadc32bc42da074b68073915a)

另外关于薪资范围的bug也修复了
