### ISSUE TITLE
 作者牛逼

### ISSUE THREAD

**Issue by vayocc** [yangfeng20/boss_batch_push#34]
本来我说用rpa写一个批量投递的给自己用，没想到搜到了这个脚本。亲自好用

**Comment by yangfeng20** [comment]
感谢支持

**Comment by vayocc** [comment]
猎头有办法屏蔽吗，我按照公司排除某互联网,某知名,某大型 这样行吗？

**Comment by yangfeng20** [comment]
暂时你可以这么搞，后面看有空加上这么一个功能把

**Comment by vayocc** [comment]
可以有工作名排除的功能吗，广撒网的时候比如我搜java全栈，他还是会推送给c#,c++,python这种岗位，就很浪费每天100名额。 或者您告诉我在哪改，我去改一下

**Comment by yangfeng20** [comment]
那就是工作名包含的筛选啊，你的工作名包含筛选可以填关键字，java

**Comment by vayocc** [comment]
我的意思是说，比如我搜java高级开发工程师，他会同时搜出来android高级开发工程师以及高级开发工程师，android的dj肯定是不符合的，高级的可能符合java，所以要把android的过滤掉。

**Comment by yangfeng20** [comment]
你说的搜索过滤是boss的，我说的按java关键词去过滤，是脚本的。例如你搜索java高级开发，但是会出现安卓开发啥的，你应该在脚本的【工作名包含】中添加(java)关键字。这样就仅会投递包含java关键字的工作

![image](https://github.com/yangfeng20/boss_batch_push/assets/83114564/3ff2fcb3-47fa-4493-9a65-af4a60d4e13a)

**Comment by apex-cmyk** [comment]
云手机结合RPA工具，会是未来个人的”数字智能孪生体“的雏形么 ？最近在使用亚矩阵云手机平台的时候，发现他们就是这样宣传云手机未来的场景的。
