### ISSUE TITLE
很好用，但是

### ISSUE THREAD

**Issue by zitian-gao** [yangfeng20/boss_batch_push#35]
如果我第一天投了100个岗位，第二天继续投会发现重复投了很多第一天的，怎么解决？

**Comment by yangfeng20** [comment]
好的，我了解一下情况。你说的重复投递，是指同一个公司的同一个职位的同一个招聘人员吗？你是怎么判断是否为重复投递的，发送了多次自定义招呼语吗？你页面上第二天还未投递时，显示的是立即投递吗，还是继续沟通？你是重新开的页面，还是昨天旧的页面？能提供一下详细的截图吗，我好排查一点。详细情况最好页描述清楚点，感谢。

**Comment by yangfeng20** [comment]
你是刷新页面之后，还是投递了重复的岗位？你是说又发送了一遍自定义招呼语吗，按照代码逻辑是会过滤掉的。你刷新之后之前投递过的岗位是显示的立即沟通，还是继续沟通啊。代码逻辑里面会过滤掉。

![image](https://github.com/yangfeng20/boss_batch_push/assets/83114564/e361235c-dbfb-4c16-8eca-0e927106abdb)

我理解你在刷新页面的情况下，会走到场景2，但是这里会过滤已经投递过的岗位的。

**Comment by iconFehu** [comment]
为啥你们的都可以用，我的连怎么用都不知道，是需要自己改代码吗
