### ISSUE TITLE
boss页面打开不显示

### ISSUE THREAD

**Issue by wangzhiwei61** [yangfeng20/boss_batch_push#37]
大佬，在油猴上安装完插件，没有显示icon，是不是我没找到地方还是操作不对，如果有空可以回复我一下吗?
![image](https://github.com/yangfeng20/boss_batch_push/assets/106916990/fcccd30f-0c9a-4b42-b0f1-fce29cd88164)

**Comment by yangfeng20** [comment]
不是在这里，要紧职位筛选页面啊
https://www.zhipin.com/web/geek/job
