### ISSUE TITLE
会莫名停止投递，再次投递时会导致有一些公司发送了两次消息

### ISSUE THREAD

**Issue by HK-bruc1** [yangfeng20/boss_batch_push#38]
先谢谢作者，一次一次投递确实难，有了这么就可以海投了。
但是二次投递问题，应该会影响第一影响吧？毕竟一看就不是手动发的。<(￣︶￣)↗[GO!]

**Comment by yangfeng20** [comment]
1.2.3版本已修复，请更新使用。
[fix:重复投递导致的重复发送自定义招呼问题](https://github.com/yangfeng20/boss_batch_push/commit/b01a19b88996339406b97368e5546402d514acd7)
