### ISSUE TITLE
投递失败;前端开发工程师 广州·白云区·嘉禾 原因：请求不合法(121).

### ISSUE THREAD

**Issue by EnSheep** [yangfeng20/boss_batch_push#41]
> 一直说请求不合法，是接口改变了吗，还是boss那边做了更改
![微信截图_20240719093358](https://github.com/user-attachments/assets/f88c18bb-5f61-4546-bd05-80fdc35cda85)

**Comment by yangfeng20** [comment]
更新新版本哟，新版本已经修复了

**Comment by yangfeng20** [comment]
https://github.com/yangfeng20/boss_batch_push/pull/40
