### ISSUE TITLE
添加个“工作名排除”

### ISSUE THREAD

**Issue by chenli1107** [yangfeng20/boss_batch_push#42]
场景：有些工作名写了岗位的特定要求，脚本目前没法排除。建议添加个“工作名排除”。

下图为我自己改造的："工作名包含"对我无用，描述改为了"工作名排除"、判断if做了反向判断
![image](https://github.com/user-attachments/assets/cbb3951f-9893-465f-bc18-efdcf9b13fce)

**Comment by yangfeng20** [comment]
理解你的需求了，不想正向筛选工作名称，就像排除一些不需要的。
你可以将你修改之后的版本提交一个pr，可以合并到当前仓库并发布的。感谢

**Comment by chenli1107** [comment]
> 理解你的需求了，不想正向筛选工作名称，就像排除一些不需要的。 你可以将你修改之后的版本提交一个pr，可以合并到当前仓库并发布的。感谢

已提交。。

**Comment by yangfeng20** [comment]
感谢你的提交，代码已经合并了。并在[Greasy Fork](https://greasyfork.org/zh-CN)发布了新版本。同时你的贡献也添加进入readme中。再次感谢你的提交。
