### ISSUE TITLE
不能发送自定义的打招呼语

### ISSUE THREAD

**Issue by leblos** [yangfeng20/boss_batch_push#47]
不能发送自定义的打招呼语，点击了保存配置

**Comment by yangfeng20** [comment]
消息页面的消息实时同步时通过websocket同步的。但是这个消息是自己通过websocket发送的。他显示有滞后性。你刷新下看看有没有。如果还是没有的话。你看看在发送消息时，控制台有没有报错。最好有截图。更方便排查。

**Comment by leblos** [comment]
![image](https://github.com/user-attachments/assets/a1b740e8-4794-49bf-9b8a-6b86bbbb30b2)
![image](https://github.com/user-attachments/assets/93ea6bad-e2f8-4be9-996b-15412f85e7ef)
出现了错误，点进去是第44行代码

**Comment by yangfeng20** [comment]
你是不是没有更新脚本啊，你现在使用的是什么版本。更新到1.2.3看看

**Comment by yangfeng20** [comment]
参考：https://github.com/yangfeng20/boss_batch_push/issues/39

**Comment by leblos** [comment]
刚刚点了更新，说未发现新版本。而且显示的是投递成功和#39不一样

**Comment by yangfeng20** [comment]
你现在是啥版本啊。

**Comment by yangfeng20** [comment]
ok，到时候我看看。可能是boss又更新了

**Comment by leblos** [comment]
1.2.3刚刚又重新装了一遍，还是不行应该是boss更新了。麻烦到时候看看，辛苦了

**Comment by vayocc** [comment]
是的，我这边也不行了

**Comment by yangfeng20** [comment]
已修复，详情请查看：[46b8834d5e25de813602f0da7df3c196d2f86a5c](https://github.com/yangfeng20/boss_batch_push/commit/46b8834d5e25de813602f0da7df3c196d2f86a5c)

原因是上次boss更新了之后，换了一个token的获取方式。当时是可行的。但是现在不行了。

**Comment by yangfeng20** [comment]
请更新到1.2.4版本使用

**Comment by leblos** [comment]
![image](https://github.com/user-attachments/assets/5793b512-7cb7-4dd4-972f-3f7f59f4a21b)
已经更新至1.2.4版本但是还是报错

**Comment by yangfeng20** [comment]
我成功的啊，你确定你更新了吗？
![image](https://github.com/user-attachments/assets/d330e77b-f0dc-4c39-939b-055bd28134d9)
![image](https://github.com/user-attachments/assets/f4c07609-9dab-42a0-b6c5-f3dc1d89f2ea)

你可以尝试重新确认一下版本重新安装下。在尝试重新登录一下，刷新一下页面。

**Comment by leblos** [comment]
可以发送了，感谢

**Comment by yangfeng20** [comment]
你之前不能发送是啥原因啊。

**Comment by leblos** [comment]
我也不知道，之前插件也更新到1.2.4了。我重新装了就好了
