### ISSUE TITLE
能有APP模式的？

### ISSUE THREAD

**Issue by DatangST** [yangfeng20/boss_batch_push#48]
能有APP模式的？因为网页搜索出来的信息特别少

**Comment by yangfeng20** [comment]
这种脚本本身就是依赖的网页，所有他是不能直接作用在app上面的。
你如果想用手机批量投递的话，可以下载支持脚本插件的浏览器。
例如kiwi浏览器
https://kiwibrowser.com/

**Comment by vayocc** [comment]
突发奇想，使用alook浏览器，添加脚本后发现不会自己弹出来批量投敌的按钮，果然手机端还是不行

**Comment by yangfeng20** [comment]
是不是修改UA 为电脑才行。然后你打开控制台看看，有没有相关报错

**Comment by vayocc** [comment]
我使用的是电脑端的页面，是直接把脚本添加到他内置的js扩展里面的，然后我尝试了使用手动模式激活脚本，他说js有错， 控制台打不开，嗨呀挺麻烦的

**Comment by yangfeng20** [comment]
我试了下，支持扩展的浏览器是没问题的。
![11da10621f467ba0735bffd48b38033](https://github.com/user-attachments/assets/e6fb9ec3-8415-4b2f-9d17-8fbb4dd97d30)

**Comment by vayocc** [comment]
这浏览器直接支持篡改猴啊，我是直接放在alook的扩展脚本里面的，您用这用的什么浏览器呢，不知道ios 有没有

**Comment by vayocc** [comment]
好，这边买了ios的Tampermonkey 可以正常运行了，之前用的alook浏览器没有找到下载扩展的地方，我是直接把脚本复制到alook设置里面的扩展脚本的地方，他报错了，可能不兼容Tampermonkey脚本吧

**Comment by vayocc** [comment]
哈哈但是ios有一点，应用后台运行了脚本就不走了， 熄屏好想也不会走
