### ISSUE TITLE
请问 未加载到本地配置 要怎么解决呢？

### ISSUE THREAD

**Issue by FocusOn1** [yangfeng20/boss_batch_push#49]
作者你好！我在使用你的脚本的时候出现了`表示未加载到本地配置`，请问应该怎么解决呢？
我的尝试方法有：
1、换浏览器
2、更换成最新版本1.2.4
但是全都没有用！

下面是我的截图：
![image](https://github.com/user-attachments/assets/c3e94148-50ac-4321-8f9d-525af1f3a4ad)
![image](https://github.com/user-attachments/assets/17e23204-8aea-4914-b22d-5c93f50491e5)

**Comment by yangfeng20** [comment]
在第一次运行时是加载不了本地配置的。因为还没有使用过，也就不存在配置。在你保存配置之后，就能加载到配置了。
然后关闭你的pr，我看是把【// @include      https://www.zhipin.com】删除掉了。这个是限定脚本运行在那些网址的。和你的这个问题没有关系。

具体你所说的不能够使用，是体现在哪方面呢？
