### ISSUE TITLE
好像有点问题

### ISSUE THREAD

**Issue by Ser-MingShao** [yangfeng20/boss_batch_push#5]
![image](https://github.com/yangfeng20/boss_batch_push/assets/67584847/67b5e23b-d611-4715-8a46-1d5125f33830)
我运行测试了一下,发现.....一共投递0份......,而且全都没有自动联系HR.....
![93a5a6d54b93e28f2270937a73c2587](https://github.com/yangfeng20/boss_batch_push/assets/67584847/a1201508-893e-4dcb-9045-6ff9019ccbc8)

**Comment by yangfeng20** [comment]
你这是不是把这些都沟通过了😳

**Comment by yangfeng20** [comment]
你这里使用的好像还是老版本，你升级之后再试试

**Comment by Ser-MingShao** [comment]
我直接在你仓库内复制的main.js文件内容的

**Comment by Ser-MingShao** [comment]
按理来说应该不会出现版本问题，我好像也没沟通，它自己跑的

**Comment by Ser-MingShao** [comment]
![image](https://github.com/yangfeng20/boss_batch_push/assets/67584847/f5a0fed1-fe46-461b-908e-706bc667b9dd)
就不知道咋回事了

**Comment by yangfeng20** [comment]
不能使用github上面最新的代码；这个代码有点问题我，好像有个依赖添加不了。您使用greasyfork上最新的版本：
https://greasyfork.org/zh-CN/scripts/468125

**Comment by Ser-MingShao** [comment]
好的好的，谢谢

**Comment by yangfeng20** [comment]
记得重新开一下浏览器，然后点一下重置按钮

**Comment by Ser-MingShao** [comment]
我按照你的方法去尝试了重启浏览器，并重置，出现了这种一直在等待的现象，请问这是什么问题
![image](https://github.com/yangfeng20/boss_batch_push/assets/67584847/0ffc57b3-0d56-43b9-bd86-87181618e791)

**Comment by yangfeng20** [comment]
你可以在jobDetailHandler中打几个日志看看，正常来说走到这里就没问题了
![image](https://github.com/yangfeng20/boss_batch_push/assets/83114564/4c718d83-6868-4ef1-bed8-b16fb42cdcda)
