### ISSUE TITLE
[Feature Request] 自定义随机间隔和保存填写结果？

### ISSUE THREAD

**Issue by xwxb** [yangfeng20/boss_batch_push#53]
前者我已经实现了，后者我不太会写，看作者什么时候有空实现下，或者指点一下怎么写

每天要重新写还是其次，主要不知道为什么有个bug，他会帮你自动刷新，导致需要重新填和开始

**Comment by yangfeng20** [comment]
你所说的随机间隔，是指每次投递之后间隔多少时间再去投递下一份吗？
后面你说的保存填写结果是？
表单你点击保存就会保存的啊

**Comment by xwxb** [comment]
> 你所说的随机间隔，是指每次投递之后间隔多少时间再去投递下一份吗？ 后面你说的保存填写结果是？ 表单你点击保存就会保存的啊

是的，我怕太快会被检测。
确实是，不好意思，我没发现，sb了。打扰了抱歉

**Comment by yangfeng20** [comment]
其实你说的随机间隔，这个时间也是有的。在代码中已经实现了这个功能的，可以直接使用的。
![image](https://github.com/user-attachments/assets/ed56ec5d-aea6-46d4-804a-ed76772d5fd6)

**Comment by xwxb** [comment]
> 其实你说的随机间隔，这个时间也是有的。在代码中已经实现了这个功能的，可以直接使用的。
> ![image](https://github.com/user-attachments/assets/ed56ec5d-aea6-46d4-804a-ed76772d5fd6)
> 

好的 感谢🥰

**Comment by yangfeng20** [comment]
这不给我点个start啊😎
感谢感谢！🤩

**Comment by xwxb** [comment]
> 这不给我点个start啊😎 感谢感谢！🤩

早就点了 😆
