### ISSUE TITLE
依然会重复投递，大佬帮看看

### ISSUE THREAD

**Issue by RickieWen** [yangfeng20/boss_batch_push#55]
用的是oop-self-req-main.js 里面的代码，15点多批量跑了一批。16点也刷新页面了，职位列表整个刷新，没点到职位详情页面，然后又开始跑批，然后发现15点多的岗位又再打招呼一次。随后点到某个岗位详情查看，不是「立即沟通」，而是「继续沟通」，不知道为啥会重复投递呢？看过前面的issue，说是代码里面有判断过滤，但是为啥还是出现了。而且不是一个岗位出现这个问题，是很多，几乎所有前面投的，都再发一遍了。见下图
<img width="525" alt="image" src="https://github.com/user-attachments/assets/0f53b8cd-a297-45a9-9c13-fc0f9cfccc42">
<img width="820" alt="image" src="https://github.com/user-attachments/assets/97ad43ee-d652-469c-94e8-ee8b778848f7">

**Comment by yangfeng20** [comment]
已修复，请更新到1.2.5版本使用
改动详情：https://github.com/yangfeng20/boss_batch_push/commit/977c03a9994f8276c5e70367054a5ccc5bd696dc

**Comment by vayocc** [comment]
哈哈其实我感觉重复投也不错，有一家大公司就是我重复投最后邀请我面了一下，但是他们要求太高了

**Comment by yangfeng20** [comment]
😂

**Comment by RickieWen** [comment]
感谢大佬，很好用，解决了我等牛马减少刷boss的时间

**Comment by RickieWen** [comment]
> 哈哈其实我感觉重复投也不错，有一家大公司就是我重复投最后邀请我面了一下，但是他们要求太高了

不过也有弊端，比如有些已经要了简历了，然后再给人家发一遍打招呼语，感觉很傻呀！！！
