### ISSUE TITLE
很好用，可以考虑增加一个不重复投递功能么

### ISSUE THREAD

**Issue by mylc2010** [yangfeng20/boss_batch_push#56]
把所有投递成功的存储到localStorage中，投递时进行比对是否在这个里面

**Comment by yangfeng20** [comment]
现在都是实时拿的接口数据来判断是否沟通过。应该是不会重复的。你使用的是1.2.5版本吗

**Comment by mylc2010** [comment]
是的，目前是这个版本，有同一个岗位连续投递的情况呢~可能是已沟通接口获取到的沟通过的岗位不全把

**Comment by yangfeng20** [comment]
就是通过当前job去获取是否已经沟通过哟，投递前单条获取的。不是批量。

**Comment by yangfeng20** [comment]
你是怎么判断重复投递的，发了两次自定义招呼语吗

**Comment by yangfeng20** [comment]
你的控制台还在不，可以在控制台日志中搜索那个岗位的关键字。可以看到整个链路。

**Comment by yangfeng20** [comment]
感谢
