### ISSUE TITLE
插件失效？

### ISSUE THREAD

**Issue by lfyuoi** [yangfeng20/boss_batch_push#58]
没有反应，不显示插件

**Comment by yangfeng20** [comment]
检查下你的油猴版本；油猴5.3.2之后的版本需要打开开发者模式，才能运行脚本。这是油猴的限制。然后需要去工作列表页面

**Comment by naiyouweibaomihua** [comment]
> 检查下你的油猴版本；油猴5.3.2之后的版本需要打开开发者模式，才能运行脚本。这是油猴的限制。然后需要去工作列表页面

原来如此，谢谢
