### ISSUE TITLE
你好，油猴版本一定得是4.18.1吗，我用的是最新版4.19.0，安装脚本启用后，页面没变化，没有你图里展示的那样的功能区

### ISSUE THREAD

**Issue by Arvin225** [yangfeng20/boss_batch_push#6]
如题，如下图
![image](https://github.com/yangfeng20/boss_batch_push/assets/60811406/3a913b7b-41df-40dd-8068-c70d4b310879)

**Comment by yangfeng20** [comment]
应该是任意版本都是可以的，你可以重新刷新一下，打开一下控制台，是不是有报错信息




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月24日(星期一) 中午1:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [yangfeng20/boss_batch_push] 你好，油猴版本一定得是4.18.1吗，我用的是最新版4.19.0，安装脚本启用后，页面没变化，没有你图里展示的那样的功能区 (Issue #6)





 
如题，如下图

**Comment by Arvin225** [comment]
> 

确实有一个错误，这个要怎么搞啊，另外我在脚本编辑页面那，这行代码也是有警告的，还有其他几行代码也有警告
![image](https://github.com/yangfeng20/boss_batch_push/assets/60811406/b94d744f-1be5-477f-b134-c43892774d18)

**Comment by yangfeng20** [comment]
你用https://greasyfork.org/zh-CN/scripts/468125-boss-batch-push-boss
这里1.1.2的版本，这个新版本有点问题，有个依赖无法引入
&nbsp;


maple
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月24日(星期一) 下午2:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yangfeng20/boss_batch_push] 你好，油猴版本一定得是4.18.1吗，我用的是最新版4.19.0，安装脚本启用后，页面没变化，没有你图里展示的那样的功能区 (Issue #6)





   
确实有一个错误，这个要怎么搞啊，另外我在脚本编辑页面那，这行代码也是有警告的，还有其他几行代码也有警告

**Comment by Arvin225** [comment]
> 你用https://greasyfork.org/zh-CN/scripts/468125-boss-batch-push-boss 这里1.1.2的版本，这个新版本有点问题，有个依赖无法引入 &nbsp; maple ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年7月24日(星期一) 下午2:01 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yangfeng20/boss_batch_push] 你好，油猴版本一定得是4.18.1吗，我用的是最新版4.19.0，安装脚本启用后，页面没变化，没有你图里展示的那样的功能区 (Issue #6) 确实有一个错误，这个要怎么搞啊，另外我在脚本编辑页面那，这行代码也是有警告的，还有其他几行代码也有警告 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

ok，有用
