### ISSUE TITLE
8.24开始好像用不了了

### ISSUE THREAD

**Issue by chanjamin** [yangfeng20/boss_batch_push#8]

**Comment by yangfeng20** [comment]
我最近看看，改改代码，很快就可以了，记得点一个star关注一下哟




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月24日(星期四) 下午3:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [yangfeng20/boss_batch_push] 8.24开始好像用不了了 (Issue #8)

**Comment by yangfeng20** [comment]
新版已经发布了，你可以试试新版
